### ISSUE TITLE
Android not running

### ISSUE THREAD

**Issue by miclovich** [lubegamark/pima#82]
Neither `react-native run-android ` or `react-native android` or `npm run android` work... I did get the iOS up and running. Then it died :-( It could help to test it independently or using a clean computer. Great work so far!

![screen shot 2017-05-27 at 10 27 07 pm](https://cloud.githubusercontent.com/assets/122275/26523902/af405eaa-432b-11e7-8b58-7910932437ef.png)

**Comment by kraib** [comment]
Currently uses android api level 23 and react-native-cli: 1.0.0 But working on a docker image to make the deployment more uniform and smooth.

**Comment by miclovich** [comment]
Update the README 

Thanks. I'll downgrade.
